version: '3.8'

services:
  backend:
    image: amadeus-backend-image
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network
  
  frontend:
    image: amadeus-frontend-image
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
